# Generated by Django 5.2.4 on 2025-08-20 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='название')),
                ('slug', models.SlugField(max_length=30)),
            ],
            options={
                'verbose_name': 'Категорию',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='DevelopersInspirers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('photo', models.ImageField(upload_to='uploads_model', verbose_name='Фото')),
                ('describt', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Разработчики и вдохновители',
            },
        ),
        migrations.CreateModel(
            name='Folkcreate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('slug', models.SlugField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Название')),
                ('ingredients', models.CharField(max_length=200, verbose_name='Ингредиенты')),
                ('time_to_cook', models.IntegerField(blank=True, default=0, verbose_name='Время готовки')),
                ('content', models.TextField(max_length=1000, verbose_name='Описание блюда')),
                ('slug', models.SlugField(max_length=30, unique=True, verbose_name='Ссылка')),
                ('is_published', models.BooleanField(default=False, verbose_name='Статус')),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='photo/%y/%m/%d', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Рецепты',
                'verbose_name_plural': 'Рецепты',
                'ordering': ['-slug'],
            },
        ),
        migrations.CreateModel(
            name='TagPosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UploadFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads_model', verbose_name='Файл')),
            ],
        ),
    ]
